In [1]:
!pip install --upgrade pandas-datareader --quiet

In [2]:
!pip install --upgrade pandas --quiet

In [3]:
import pandas_datareader as reader
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt

from dateutil.relativedelta import relativedelta

%matplotlib inline

In [4]:
wiki = 'https://en.wikipedia.org/wiki/'
tickersDJIA = pd.read_html(wiki+'Dow_Jones_Industrial_Average')[1].Symbol.to_list()

In [5]:
print(tickersDJIA)

['MMM', 'AXP', 'AMGN', 'AAPL', 'BA', 'CAT', 'CVX', 'CSCO', 'KO', 'DIS', 'DOW', 'GS', 'HD', 'HON', 'IBM', 'INTC', 'JNJ', 'JPM', 'MCD', 'MRK', 'MSFT', 'NKE', 'PG', 'CRM', 'TRV', 'UNH', 'VZ', 'V', 'WBA', 'WMT']

In [6]:
# Get prices for DJIA components
start_date = dt.datetime(2018,1,31)
end_date = dt.datetime(2020,1,31)

df = reader.get_data_yahoo(tickersDJIA, start_date, end_date)['Adj Close']
df.head()

/usr/local/lib/python3.7/dist-packages/pandas_datareader/base.py:272: SymbolWarning: Failed to read symbol: 'MMM', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

Symbols,AXP,AMGN,AAPL,BA,CAT,CVX,CSCO,KO,DIS,DOW,...,NKE,PG,CRM,TRV,UNH,VZ,V,WBA,WMT,MMM
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-31,93.251419,162.849075,39.923687,337.712097,145.480331,102.369659,36.304306,41.178398,105.682114,NaN,...,65.316170,76.464363,113.910004,134.844238,221.443115,44.258865,120.699440,64.314690,98.077095,NaN
2018-02-01,93.814323,162.420181,40.007145,340.161285,144.997711,102.549332,36.444130,41.057266,107.452065,NaN,...,64.770416,76.030411,112.739998,134.916214,219.984116,44.447128,122.147095,64.998344,97.083450,NaN
2018-02-02,90.699677,163.689377,38.271229,332.508728,140.752502,96.840782,35.771183,40.434265,105.711281,NaN,...,64.358727,74.613396,110.779999,133.072342,216.860504,43.366642,117.473801,62.861927,96.126602,NaN
2018-02-05,86.318558,152.958252,37.315052,313.420319,135.023743,91.973442,33.892170,38.842155,101.821266,NaN,...,61.649181,71.788284,107.650002,127.288963,205.768692,41.336647,112.965645,60.187134,92.087578,NaN
2018-02-06,88.354301,154.621292,38.874516,324.884796,139.787338,95.697456,35.106976,38.651798,103.250854,NaN,...,62.443859,72.957314,109.570000,126.686302,210.594482,41.606762,116.560509,61.349346,92.832817,NaN

#### Calculate monthly returns by cumulating daily returns
---

In [7]:
# Get monthly returns
mth_ret = df.pct_change().resample('M').agg(lambda x: (x+1).prod() -1)
mth_ret

Symbols,AXP,AMGN,AAPL,BA,CAT,CVX,CSCO,KO,DIS,DOW,...,NKE,PG,CRM,TRV,UNH,VZ,V,WBA,WMT,MMM
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2018-02-28,-0.019014,-0.004788,0.068185,0.027169,-0.050068,-0.098252,0.077997,-0.091826,-0.050704,0.000000,...,-0.017444,-0.090572,0.020543,-0.072839,-0.044852,-0.117071,-0.008661,-0.079247,-0.155628,0.0
2018-03-31,-0.043380,-0.072319,-0.058051,-0.094779,-0.046886,0.018942,-0.042206,0.013729,-0.026367,0.000000,...,-0.005804,0.009679,0.000430,0.004199,-0.050634,0.001675,-0.027005,-0.049644,-0.005661,0.0
2018-04-30,0.062615,0.023463,-0.015019,0.017323,-0.015560,0.097071,0.040943,-0.005066,-0.001095,0.000000,...,0.029350,-0.079094,0.040327,-0.052283,0.104673,0.044981,0.060692,0.014969,-0.005732,0.0
2018-05-31,-0.004557,0.037405,0.135124,0.061029,0.052300,0.002189,-0.035674,-0.004860,-0.008572,0.000000,...,0.049861,0.011473,0.068931,-0.023404,0.021616,-0.034043,0.031921,-0.055351,-0.061045,0.0
2018-06-30,-0.003052,0.027670,-0.009418,-0.047279,-0.106905,0.017136,0.007492,0.029084,0.053685,0.000000,...,0.112849,0.066831,0.054666,-0.042360,0.019452,0.055381,0.013234,-0.037987,0.037679,0.0
2018-07-31,0.019156,0.064792,0.027983,0.061965,0.066424,-0.001265,-0.009537,0.063155,0.092194,0.000000,...,-0.034764,0.045529,0.005499,0.063757,0.032119,0.038336,0.032389,0.126625,0.041798,0.0
2018-08-31,0.064912,0.023505,0.200422,-0.033164,-0.034423,-0.052857,0.129582,-0.044177,-0.013561,0.000000,...,0.071414,0.025594,0.113234,0.011219,0.060185,0.052866,0.075843,0.020350,0.080542,0.0
2018-09-30,0.004812,0.037435,-0.008303,0.084921,0.098236,0.032247,0.018421,0.045162,0.043921,0.000000,...,0.030657,0.003376,0.041590,-0.008603,-0.005671,-0.018025,0.021785,0.063303,-0.020342,0.0
2018-10-31,-0.031827,-0.069950,-0.030478,-0.045819,-0.199336,-0.086932,-0.053252,0.036588,-0.018043,0.000000,...,-0.114259,0.074896,-0.137018,-0.035310,-0.017629,0.081151,-0.081551,0.094238,0.067831,0.0
2018-11-30,0.092865,0.087734,-0.181198,-0.018313,0.118282,0.075705,0.046339,0.060955,0.005748,0.000000,...,0.004037,0.065742,0.040221,0.041876,0.080004,0.056227,0.029847,0.067159,-0.026226,0.0
2018-12-31,-0.150975,-0.065210,-0.116698,-0.069962,-0.063389,-0.085337,-0.094840,-0.060516,-0.043203,0.000000,...,-0.013046,-0.027405,-0.040558,-0.075786,-0.114586,-0.067662,-0.068944,-0.192984,-0.040877,0.0
2019-01-31,0.081833,-0.038835,0.055154,0.195721,0.054668,0.053865,0.099842,0.016473,0.017054,0.000000,...,0.104397,0.057800,0.109513,0.048351,0.084618,-0.010412,0.023268,0.057515,0.028771,0.0
2019-02-28,0.049075,0.023728,0.044776,0.146648,0.031391,0.053485,0.094735,-0.057968,0.011836,0.000000,...,0.047020,0.021561,0.076857,0.058706,-0.103553,0.033781,0.099018,-0.008786,0.032975,0.0
2019-03-31,0.014479,-0.000526,0.097026,-0.133057,-0.013470,0.030105,0.042882,0.042547,-0.016040,0.036747,...,-0.015203,0.055809,-0.032264,0.038055,0.024704,0.038826,0.054483,-0.111252,-0.009448,0.0
2019-04-30,0.076350,-0.056111,0.056436,-0.009779,0.035243,-0.025329,0.042864,0.046948,0.233631,0.098780,...,0.042988,0.030578,0.044074,0.048046,-0.057389,-0.022844,0.052756,-0.153311,0.054445,0.0
2019-05-31,-0.021496,-0.062373,-0.124213,-0.090332,-0.140654,-0.042394,-0.070063,0.001427,-0.035993,-0.163727,...,-0.119268,-0.033527,-0.084306,0.012661,0.037456,-0.049659,-0.017344,-0.071178,-0.008373,0.0
2019-06-30,0.076105,0.105459,0.130519,0.065572,0.137551,0.093017,0.051893,0.044524,0.057558,0.054534,...,0.088281,0.065494,0.002113,0.032819,0.013609,0.051150,0.075745,0.108026,0.089215,0.0
2019-07-31,0.010685,0.012481,0.076394,-0.062718,-0.026465,-0.010688,0.018630,0.033582,0.030476,-0.017644,...,0.024777,0.083488,0.018256,-0.019395,0.020491,-0.022374,0.025641,-0.003292,-0.000996,0.0
2019-08-31,-0.032162,0.126048,-0.016461,0.073808,-0.096225,-0.033952,-0.155054,0.045791,-0.040207,-0.105211,...,-0.015247,0.018553,0.010162,0.002319,-0.060279,0.052289,0.017309,-0.051960,0.040247,0.0
2019-09-30,-0.017363,-0.072428,0.072962,0.044989,0.061428,0.007475,0.055544,-0.003670,-0.050561,0.117757,...,0.111479,0.034517,-0.048888,0.017230,-0.066902,0.037827,-0.048723,0.080484,0.038684,0.0
2019-10-31,-0.004662,0.102010,0.110684,-0.106605,0.099542,-0.020742,-0.031171,-0.000184,-0.003069,0.059601,...,-0.046529,0.007440,0.054231,-0.118569,0.162801,0.012247,0.039824,-0.009582,-0.011965,0.0
2019-11-30,0.024216,0.107994,0.077554,0.083572,0.050290,0.018462,-0.046306,-0.011595,0.166718,0.070575,...,0.046722,-0.019677,0.040897,0.043186,0.107519,-0.003804,0.033316,0.096093,0.015606,0.0
2019-12-31,0.036380,0.027053,0.098784,-0.110383,0.020383,0.028857,0.058486,0.036517,-0.040134,0.025482,...,0.083645,0.023267,-0.001535,0.007771,0.054455,0.019256,0.018373,-0.010738,0.002377,0.0
2020-01-31,0.046832,-0.103787,0.054010,-0.022993,-0.104338,-0.110945,-0.034446,0.055104,-0.043698,-0.158231,...,-0.049452,0.003686,0.120942,-0.038919,-0.073236,-0.021847,0.058914,-0.137551,-0.036604,0.0

In [8]:
# Calculate cumulative returns over the past 11 months: 12M - 1M
past_11 = (mth_ret+1).rolling(11).apply(np.prod)-1
past_11

Symbols,AXP,AMGN,AAPL,BA,CAT,CVX,CSCO,KO,DIS,DOW,...,NKE,PG,CRM,TRV,UNH,VZ,V,WBA,WMT,MMM
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-11-30,0.141894,0.152214,0.082608,-0.002270,-0.151840,-0.014529,0.178616,0.095675,0.071302,0.000000,...,0.113583,0.124632,0.253270,-0.115475,0.204300,0.155004,0.148307,0.152019,-0.067306,0.0
2018-12-31,-0.030504,0.077078,-0.043730,-0.072073,-0.205604,-0.098626,0.066836,0.029369,0.025019,0.000000,...,0.099055,0.093812,0.202440,-0.182510,0.066304,0.076854,0.069139,-0.070302,-0.105432,0.0
2019-01-31,0.069162,0.040230,-0.055396,0.080194,-0.118018,0.053428,0.088455,0.152121,0.098182,0.000000,...,0.235342,0.272266,0.307269,-0.075655,0.210841,0.206939,0.103574,0.067788,0.089929,0.0
2019-02-28,0.172494,0.147929,0.047721,0.368287,-0.045583,0.089140,0.244077,0.070636,0.141272,0.000000,...,0.300979,0.287239,0.407137,-0.025482,0.143347,0.245624,0.246510,0.113695,0.132280,0.0
2019-03-31,0.119381,0.121023,0.166903,0.166026,-0.043556,0.022658,0.246394,0.121871,0.124196,0.036747,...,0.244669,0.475806,0.308951,0.067411,0.060578,0.238288,0.239213,-0.024803,0.128049,0.0
2019-04-30,0.210361,0.019969,0.086012,0.088211,-0.059060,-0.005422,0.347906,0.180277,0.398834,0.139157,...,0.236520,0.503682,0.278512,0.145505,-0.021439,0.252644,0.264234,-0.125931,0.266797,0.0
2019-05-31,0.187968,-0.069399,-0.039842,0.039036,-0.094617,-0.063632,0.244146,0.148556,0.279781,-0.047354,...,-0.021392,0.362229,0.110044,0.211320,-0.004157,0.127971,0.226082,-0.156088,0.210576,0.0
2019-06-30,0.254350,-0.033857,0.055929,0.042565,-0.034230,0.024763,0.321311,0.128429,0.239196,0.004598,...,0.103358,0.388241,0.106307,0.176090,-0.022017,0.141891,0.277572,-0.170019,0.265675,0.0
2019-07-31,0.190477,-0.044264,-0.053170,0.010696,-0.026270,0.070388,0.191526,0.220230,0.294517,-0.013127,...,0.055330,0.466606,0.011920,0.140484,-0.058633,0.060289,0.217956,-0.189250,0.170167,0.0
2019-08-31,0.146670,0.037370,-0.060959,0.000344,-0.198685,0.001743,-0.011436,0.220965,0.190194,-0.116957,...,0.008327,0.488790,-0.018613,0.153049,-0.110332,0.136210,0.212620,-0.277136,0.242539,0.0
2019-09-30,0.163800,0.034606,0.039228,0.095545,0.062292,0.105318,0.102165,0.173547,0.150781,-0.012973,...,0.265307,0.432864,0.081609,0.215846,-0.154956,0.090680,0.255963,-0.286222,0.208623,0.0
2019-10-31,0.059943,0.048185,0.409686,-0.002987,0.044490,0.006217,0.020520,0.105919,0.140692,0.045856,...,0.201583,0.354478,0.096175,0.028611,-0.090171,0.045265,0.268130,-0.337551,0.226324,0.0
2019-11-30,0.278656,0.242400,0.719699,0.161603,0.171263,0.120405,0.075239,0.163507,0.390960,0.119667,...,0.274347,0.365239,0.189239,0.161021,0.138058,0.116858,0.407412,-0.100258,0.298543,0.0
2019-12-31,0.224934,0.327567,0.790808,-0.135766,0.133187,0.093818,0.034808,0.186450,0.312747,0.148199,...,0.250402,0.320670,0.070211,0.116080,0.106409,0.150342,0.400679,-0.158329,0.265228,0.0
2020-01-31,0.222315,0.162206,0.806634,-0.263625,-0.015938,-0.076908,-0.087301,0.328859,0.240698,-0.033482,...,0.135190,0.297561,0.114024,0.013164,0.143826,0.088441,0.349567,-0.267667,0.180005,0.0

In [9]:
# Set portfolio formation date - date we are buying winners and shorting winners. Reference point for measurement
formation = dt.datetime(2019,12,31)

# End of measurement date - 1M before formation so we can skip that month
# Subtract last month to account for skipping that month
end_measurement = formation - relativedelta(months=1)

In [10]:
formation

datetime.datetime(2019, 12, 31, 0, 0)

In [11]:
end_measurement

datetime.datetime(2019, 11, 30, 0, 0)

In [12]:
# Get the past 12 months performance skipping the most recent month
ret_12 = past_11.loc[end_measurement]
ret_12

Symbols
AXP     0.278656
AMGN    0.242400
AAPL    0.719699
BA      0.161603
CAT     0.171263
CVX     0.120405
CSCO    0.075239
KO      0.163507
DIS     0.390960
DOW     0.119667
GS      0.352369
HD      0.309954
HON     0.378922
IBM     0.239541
INTC    0.267808
JNJ     0.095434
JPM     0.391864
MCD     0.121662
MRK     0.164049
MSFT    0.512438
NKE     0.274347
PG      0.365239
CRM     0.189239
TRV     0.161021
UNH     0.138058
VZ      0.116858
V       0.407412
WBA    -0.100258
WMT     0.298543
MMM     0.000000
Name: 2019-11-30 00:00:00, dtype: float64

In [13]:
# Convert series to DF
ret_12 = ret_12.to_frame().reset_index()
ret_12

   Symbols  2019-11-30 00:00:00
0      AXP             0.278656
1     AMGN             0.242400
2     AAPL             0.719699
3       BA             0.161603
4      CAT             0.171263
5      CVX             0.120405
6     CSCO             0.075239
7       KO             0.163507
8      DIS             0.390960
9      DOW             0.119667
10      GS             0.352369
11      HD             0.309954
12     HON             0.378922
13     IBM             0.239541
14    INTC             0.267808
15     JNJ             0.095434
16     JPM             0.391864
17     MCD             0.121662
18     MRK             0.164049
19    MSFT             0.512438
20     NKE             0.274347
21      PG             0.365239
22     CRM             0.189239
23     TRV             0.161021
24     UNH             0.138058
25      VZ             0.116858
26       V             0.407412
27     WBA            -0.100258
28     WMT             0.298543
29     MMM             0.000000

In [14]:
# Split stocks into quintiles by performance
ret_12['quintile'] = pd.qcut(ret_12.iloc[:,1], 5, labels=False)
ret_12

   Symbols  2019-11-30 00:00:00  quintile
0      AXP             0.278656         3
1     AMGN             0.242400         2
2     AAPL             0.719699         4
3       BA             0.161603         1
4      CAT             0.171263         2
5      CVX             0.120405         1
6     CSCO             0.075239         0
7       KO             0.163507         1
8      DIS             0.390960         4
9      DOW             0.119667         0
10      GS             0.352369         3
11      HD             0.309954         3
12     HON             0.378922         4
13     IBM             0.239541         2
14    INTC             0.267808         2
15     JNJ             0.095434         0
16     JPM             0.391864         4
17     MCD             0.121662         1
18     MRK             0.164049         2
19    MSFT             0.512438         4
20     NKE             0.274347         3
21      PG             0.365239         3
22     CRM             0.189239         2
23     TRV             0.161021         1
24     UNH             0.138058         1
25      VZ             0.116858         0
26       V             0.407412         4
27     WBA            -0.100258         0
28     WMT             0.298543         3
29     MMM             0.000000         0

In [15]:
# Define winners and losers by highest and lowest performing quintiles
winners = ret_12[ret_12.quintile == 4]
losers = ret_12[ret_12.quintile == 0]

In [16]:
# Buy and hold for one month
winners

   Symbols  2019-11-30 00:00:00  quintile
2     AAPL             0.719699         4
8      DIS             0.390960         4
12     HON             0.378922         4
16     JPM             0.391864         4
19    MSFT             0.512438         4
26       V             0.407412         4

In [17]:
# Short these for one month
losers

   Symbols  2019-11-30 00:00:00  quintile
6     CSCO             0.075239         0
9      DOW             0.119667         0
15     JNJ             0.095434         0
25      VZ             0.116858         0
27     WBA            -0.100258         0
29     MMM             0.000000         0

In [18]:
# Calculate winner return by finding the January return of the winners
winner_ret = mth_ret.loc[formation + relativedelta(months=1), df.columns.isin(winners.Symbols)]
winner_ret

Symbols
AAPL    0.054010
DIS    -0.043698
HON    -0.021356
JPM    -0.044407
MSFT    0.079455
V       0.058914
Name: 2020-01-31 00:00:00, dtype: float64

In [19]:
# Calculate losers return by finding the January return of the losers
loser_ret = mth_ret.loc[formation + relativedelta(months=1), df.columns.isin(losers.Symbols)]
loser_ret

Symbols
CSCO   -0.034446
DOW    -0.158231
JNJ     0.020566
VZ     -0.021847
WBA    -0.137551
MMM     0.000000
Name: 2020-01-31 00:00:00, dtype: float64

In [20]:
# Assume EW portfolio. Calculate profit of momentum strategy
momentum_profit = winner_ret.mean() - loser_ret.mean()
momentum_profit

0.06907133347969653

In [21]:
# Calculate profif of benchmark
djia_cumulative_ret = reader.get_data_yahoo('^DJI', start_date, end_date)['Adj Close'].pct_change().resample('M').agg(lambda x: (x+1).prod() -1)
djia_cumulative_ret

Date
2018-01-31    0.000000
2018-02-28   -0.042838
2018-03-31   -0.037000
2018-04-30    0.002491
2018-05-31    0.010458
2018-06-30   -0.005915
2018-07-31    0.047125
2018-08-31    0.021626
2018-09-30    0.019006
2018-10-31   -0.050742
2018-11-30    0.016830
2018-12-31   -0.086575
2019-01-31    0.071684
2019-02-28    0.036654
2019-03-31    0.000489
2019-04-30    0.025618
2019-05-31   -0.066855
2019-06-30    0.071929
2019-07-31    0.009936
2019-08-31   -0.017160
2019-09-30    0.019450
2019-10-31    0.004807
2019-11-30    0.037165
2019-12-31    0.017362
2020-01-31   -0.009896
Freq: M, Name: Adj Close, dtype: float64

In [22]:
print("Strategy Momentum Profit: {}".format(momentum_profit))
print("DJIA Benchmark Profit: {}".format(djia_cumulative_ret.iloc[-1]))

Strategy Momentum Profit: 0.06907133347969653
DJIA Benchmark Profit: -0.009895781327281972